services:
  - type: web
    name: random-badminton
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production

      # Đây là internal database URL (dành cho Render sử dụng nội bộ)
      - key: DATABASE_INTERNAL_URL
        value: postgresql://cps_db_user:7bEpwOCr0jdrFqaWTnmX3JHSeWpMOq1v@dpg-d1ifiaumcj7s738r7kf0-a/cps_db

      # Đánh dấu đang chạy trên Render
      - key: RENDER
        value: true

      # Flask secret key
      - key: SECRET_KEY
        value: your-secret-key
